## basic python code

In [2]:
print("hello world")

hello world

In [12]:
def double (num):
    return (num**2)
double(2)
double(3)

9

In [13]:
def square (num):
    return num*num
square(3)

9

In [14]:
website = "apple.com"
print(website)

# assigning a new value to website
website = "programiz.com"

print(website)

apple.com
programiz.com

In [15]:
aditya = "maheshwari"
print(aditya)
print("aditya")
aditya ="kanu"
print(aditya)
print("aditya")

maheshwari
aditya
kanu
aditya

In [16]:
a,b,c = 10,20.32,"aditya"
print(a,b,c)

10 20.32 aditya

In [20]:
drink = "Available"
food = None

def menu(x):
    if x == drink:
        print(drink)
    else:
        print(food)

menu(drink)
menu(food)

Available
None

In [21]:
aditya = "adi"
maheshwari = "mahesh"

def menu(x):
    if x==aditya:
        print(aditya)
    else:
        print(maheshwari)
        
menu(aditya)
menu(maheshwari)

adi
mahesh

In [22]:
fruits = ["apple", "mango", "orange"] #list
numbers = (1, 2, 3) #tuple
alphabets = {'a':'apple', 'b':'ball', 'c':'cat'} #dictionary
vowels = {'a', 'e', 'i' , 'o', 'u'} #set

print(fruits)
print(numbers)
print(alphabets)
print(vowels)

['apple', 'mango', 'orange']
(1, 2, 3)
{'a': 'apple', 'b': 'ball', 'c': 'cat'}
{'u', 'a', 'i', 'o', 'e'}

In [24]:
aditya = ["sab","jskhk","dbsh"] #list
maheshwari = (1,2,3,45,5) #tuple
kanu = {'a':'apple' , 'b':'banana','c':'carrot'} #dictionary
vowel = {"a","e","i","o","u"} # set
print(aditya,maheshwari,kanu,vowel)

['sab', 'jskhk', 'dbsh'] (1, 2, 3, 45, 5) {'a': 'apple', 'b': 'banana', 'c': 'carrot'} {'u', 'a', 'i', 'o', 'e'}

In [29]:
a=5.0
print(a ,"is of type", type(a))

5.0 is of type <class 'float'>

In [41]:
adi=[1,2,34,5,6,7,88,8,]
print(adi[0:2])
print(adi[:3])
print(adi[:-3])
adi[2]= "aditya"
print(adi)

[1, 2]
[1, 2, 34]
[1, 2, 34, 5, 6]
[1, 2, 'aditya', 5, 6, 7, 88, 8]

In [49]:
di=(1,2,34,5,6,7,88,8,)
print(di)
print(di[:-1])

(1, 2, 34, 5, 6, 7, 88, 8)
(1, 2, 34, 5, 6, 7, 88)

In [50]:
d = {1:'value','key':2}
print(type(d))

print("d[1] = ", d[1])

print("d['key'] = ", d['key'])

# Generates error
print("d[2] = ", d[2])

<class 'dict'>
d[1] =  value
d['key'] =  2

KeyError: 2

In [51]:
list("aditya")

['a', 'd', 'i', 't', 'y', 'a']

In [54]:
print('i love {0} and butter {1}' .format ('bread','butter'))

i love bread and butter butter

In [55]:
print("i like {0} and {1}".format("adi","asd"))

i like adi and asd

In [60]:
x=123.3444
print("the value of x: % 3.3f" %x)

the value of x:  123.344

In [62]:
num = int(input("the number is "))
print(type(num))

the number is 3
<class 'int'>

In [65]:
from math import sqrt
a = float(input("type the number"))
print("square of the number is " , sqrt(a))

type the number36
square of the number is  6.0

In [81]:
%%timeit
l = []
for i in range(1000):
    l.append(i*i)

290 µs ± 3.94 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [80]:
%%timeit
l = list(map(lambda x: x*x, range(1000)))

324 µs ± 7.85 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

######  List = [1,2,3,4,5,.., 1000000000.]
###### Generator = function

In [ ]:
l = [x*x for x in range(1000)]    # List Comprehension

# l = []
# for x in range(1000):
#     l.append(x*x)

In [136]:
l = (x*x for x in range(10000000000))

In [178]:
l.__next__()

1681

In [ ]:
def abc():
    return 


def abc():
    yield

In [190]:
a = [1,2]
b = [3,4]

c = a + b
c.pop(2), c

(3, [1, 2, 4])

In [180]:
a = (1,2)
b = (3,4)

a + b

(1, 2, 3, 4)

In [231]:
#"abcdefghi024"[3:6], 
#l=[i for i in "abcdefghi024"]
#l
l= list("aditya")
l

['a', 'd', 'i', 't', 'y', 'a']

In [218]:
d = {}
for key, value in enumerate(range(0,20000,2)):
    d.update({key:value})

In [219]:
%%timeit
c = {}
for key, value in d.items():
    c.update({value:key})

6.64 ms ± 194 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [237]:
#%%timeit
{value:key for key, value in enumerate(range(0,20000,2))} # dict comprehension

{0: 0,
 2: 1,
 4: 2,
 6: 3,
 8: 4,
 10: 5,
 12: 6,
 14: 7,
 16: 8,
 18: 9,
 20: 10,
 22: 11,
 24: 12,
 26: 13,
 28: 14,
 30: 15,
 32: 16,
 34: 17,
 36: 18,
 38: 19,
 40: 20,
 42: 21,
 44: 22,
 46: 23,
 48: 24,
 50: 25,
 52: 26,
 54: 27,
 56: 28,
 58: 29,
 60: 30,
 62: 31,
 64: 32,
 66: 33,
 68: 34,
 70: 35,
 72: 36,
 74: 37,
 76: 38,
 78: 39,
 80: 40,
 82: 41,
 84: 42,
 86: 43,
 88: 44,
 90: 45,
 92: 46,
 94: 47,
 96: 48,
 98: 49,
 100: 50,
 102: 51,
 104: 52,
 106: 53,
 108: 54,
 110: 55,
 112: 56,
 114: 57,
 116: 58,
 118: 59,
 120: 60,
 122: 61,
 124: 62,
 126: 63,
 128: 64,
 130: 65,
 132: 66,
 134: 67,
 136: 68,
 138: 69,
 140: 70,
 142: 71,
 144: 72,
 146: 73,
 148: 74,
 150: 75,
 152: 76,
 154: 77,
 156: 78,
 158: 79,
 160: 80,
 162: 81,
 164: 82,
 166: 83,
 168: 84,
 170: 85,
 172: 86,
 174: 87,
 176: 88,
 178: 89,
 180: 90,
 182: 91,
 184: 92,
 186: 93,
 188: 94,
 190: 95,
 192: 96,
 194: 97,
 196: 98,
 198: 99,
 200: 100,
 202: 101,
 204: 102,
 206: 103,
 208: 104,
 210: 105,
 212: 106,
 214: 107,
 216: 108,
 218: 109,
 220: 110,
 222: 111,
 224: 112,
 226: 113,
 228: 114,
 230: 115,
 232: 116,
 234: 117,
 236: 118,
 238: 119,
 240: 120,
 242: 121,
 244: 122,
 246: 123,
 248: 124,
 250: 125,
 252: 126,
 254: 127,
 256: 128,
 258: 129,
 260: 130,
 262: 131,
 264: 132,
 266: 133,
 268: 134,
 270: 135,
 272: 136,
 274: 137,
 276: 138,
 278: 139,
 280: 140,
 282: 141,
 284: 142,
 286: 143,
 288: 144,
 290: 145,
 292: 146,
 294: 147,
 296: 148,
 298: 149,
 300: 150,
 302: 151,
 304: 152,
 306: 153,
 308: 154,
 310: 155,
 312: 156,
 314: 157,
 316: 158,
 318: 159,
 320: 160,
 322: 161,
 324: 162,
 326: 163,
 328: 164,
 330: 165,
 332: 166,
 334: 167,
 336: 168,
 338: 169,
 340: 170,
 342: 171,
 344: 172,
 346: 173,
 348: 174,
 350: 175,
 352: 176,
 354: 177,
 356: 178,
 358: 179,
 360: 180,
 362: 181,
 364: 182,
 366: 183,
 368: 184,
 370: 185,
 372: 186,
 374: 187,
 376: 188,
 378: 189,
 380: 190,
 382: 191,
 384: 192,
 386: 193,
 388: 194,
 390: 195,
 392: 196,
 394: 197,
 396: 198,
 398: 199,
 400: 200,
 402: 201,
 404: 202,
 406: 203,
 408: 204,
 410: 205,
 412: 206,
 414: 207,
 416: 208,
 418: 209,
 420: 210,
 422: 211,
 424: 212,
 426: 213,
 428: 214,
 430: 215,
 432: 216,
 434: 217,
 436: 218,
 438: 219,
 440: 220,
 442: 221,
 444: 222,
 446: 223,
 448: 224,
 450: 225,
 452: 226,
 454: 227,
 456: 228,
 458: 229,
 460: 230,
 462: 231,
 464: 232,
 466: 233,
 468: 234,
 470: 235,
 472: 236,
 474: 237,
 476: 238,
 478: 239,
 480: 240,
 482: 241,
 484: 242,
 486: 243,
 488: 244,
 490: 245,
 492: 246,
 494: 247,
 496: 248,
 498: 249,
 500: 250,
 502: 251,
 504: 252,
 506: 253,
 508: 254,
 510: 255,
 512: 256,
 514: 257,
 516: 258,
 518: 259,
 520: 260,
 522: 261,
 524: 262,
 526: 263,
 528: 264,
 530: 265,
 532: 266,
 534: 267,
 536: 268,
 538: 269,
 540: 270,
 542: 271,
 544: 272,
 546: 273,
 548: 274,
 550: 275,
 552: 276,
 554: 277,
 556: 278,
 558: 279,
 560: 280,
 562: 281,
 564: 282,
 566: 283,
 568: 284,
 570: 285,
 572: 286,
 574: 287,
 576: 288,
 578: 289,
 580: 290,
 582: 291,
 584: 292,
 586: 293,
 588: 294,
 590: 295,
 592: 296,
 594: 297,
 596: 298,
 598: 299,
 600: 300,
 602: 301,
 604: 302,
 606: 303,
 608: 304,
 610: 305,
 612: 306,
 614: 307,
 616: 308,
 618: 309,
 620: 310,
 622: 311,
 624: 312,
 626: 313,
 628: 314,
 630: 315,
 632: 316,
 634: 317,
 636: 318,
 638: 319,
 640: 320,
 642: 321,
 644: 322,
 646: 323,
 648: 324,
 650: 325,
 652: 326,
 654: 327,
 656: 328,
 658: 329,
 660: 330,
 662: 331,
 664: 332,
 666: 333,
 668: 334,
 670: 335,
 672: 336,
 674: 337,
 676: 338,
 678: 339,
 680: 340,
 682: 341,
 684: 342,
 686: 343,
 688: 344,
 690: 345,
 692: 346,
 694: 347,
 696: 348,
 698: 349,
 700: 350,
 702: 351,
 704: 352,
 706: 353,
 708: 354,
 710: 355,
 712: 356,
 714: 357,
 716: 358,
 718: 359,
 720: 360,
 722: 361,
 724: 362,
 726: 363,
 728: 364,
 730: 365,
 732: 366,
 734: 367,
 736: 368,
 738: 369,
 740: 370,
 742: 371,
 744: 372,
 746: 373,
 748: 374,
 750: 375,
 752: 376,
 754: 377,
 756: 378,
 758: 379,
 760: 380,
 762: 381,
 764: 382,
 766: 383,
 768: 384,
 770: 385,
 772: 386,
 774: 387,
 776: 388,
 778: 389,
 780: 390,
 782: 391,
 784: 392,
 786: 393,
 788: 394,
 790: 395,
 792: 396,
 794: 397,
 796: 398,
 798: 399,
 800: 400,
 802: 401,
 804: 402,
 806: 403,
 808: 404,
 810: 405,
 812: 406,
 814: 407,
 816: 408,
 818: 409,
 820: 410,
 822: 411,
 824: 412,
 826: 413,
 828: 414,
 830: 415,
 832: 416,
 834: 417,
 836: 418,
 838: 419,
 840: 420,
 842: 421,
 844: 422,
 846: 423,
 848: 424,
 850: 425,
 852: 426,
 854: 427,
 856: 428,
 858: 429,
 860: 430,
 862: 431,
 864: 432,
 866: 433,
 868: 434,
 870: 435,
 872: 436,
 874: 437,
 876: 438,
 878: 439,
 880: 440,
 882: 441,
 884: 442,
 886: 443,
 888: 444,
 890: 445,
 892: 446,
 894: 447,
 896: 448,
 898: 449,
 900: 450,
 902: 451,
 904: 452,
 906: 453,
 908: 454,
 910: 455,
 912: 456,
 914: 457,
 916: 458,
 918: 459,
 920: 460,
 922: 461,
 924: 462,
 926: 463,
 928: 464,
 930: 465,
 932: 466,
 934: 467,
 936: 468,
 938: 469,
 940: 470,
 942: 471,
 944: 472,
 946: 473,
 948: 474,
 950: 475,
 952: 476,
 954: 477,
 956: 478,
 958: 479,
 960: 480,
 962: 481,
 964: 482,
 966: 483,
 968: 484,
 970: 485,
 972: 486,
 974: 487,
 976: 488,
 978: 489,
 980: 490,
 982: 491,
 984: 492,
 986: 493,
 988: 494,
 990: 495,
 992: 496,
 994: 497,
 996: 498,
 998: 499,
 1000: 500,
 1002: 501,
 1004: 502,
 1006: 503,
 1008: 504,
 1010: 505,
 1012: 506,
 1014: 507,
 1016: 508,
 1018: 509,
 1020: 510,
 1022: 511,
 1024: 512,
 1026: 513,
 1028: 514,
 1030: 515,
 1032: 516,
 1034: 517,
 1036: 518,
 1038: 519,
 1040: 520,
 1042: 521,
 1044: 522,
 1046: 523,
 1048: 524,
 1050: 525,
 1052: 526,
 1054: 527,
 1056: 528,
 1058: 529,
 1060: 530,
 1062: 531,
 1064: 532,
 1066: 533,
 1068: 534,
 1070: 535,
 1072: 536,
 1074: 537,
 1076: 538,
 1078: 539,
 1080: 540,
 1082: 541,
 1084: 542,
 1086: 543,
 1088: 544,
 1090: 545,
 1092: 546,
 1094: 547,
 1096: 548,
 1098: 549,
 1100: 550,
 1102: 551,
 1104: 552,
 1106: 553,
 1108: 554,
 1110: 555,
 1112: 556,
 1114: 557,
 1116: 558,
 1118: 559,
 1120: 560,
 1122: 561,
 1124: 562,
 1126: 563,
 1128: 564,
 1130: 565,
 1132: 566,
 1134: 567,
 1136: 568,
 1138: 569,
 1140: 570,
 1142: 571,
 1144: 572,
 1146: 573,
 1148: 574,
 1150: 575,
 1152: 576,
 1154: 577,
 1156: 578,
 1158: 579,
 1160: 580,
 1162: 581,
 1164: 582,
 1166: 583,
 1168: 584,
 1170: 585,
 1172: 586,
 1174: 587,
 1176: 588,
 1178: 589,
 1180: 590,
 1182: 591,
 1184: 592,
 1186: 593,
 1188: 594,
 1190: 595,
 1192: 596,
 1194: 597,
 1196: 598,
 1198: 599,
 1200: 600,
 1202: 601,
 1204: 602,
 1206: 603,
 1208: 604,
 1210: 605,
 1212: 606,
 1214: 607,
 1216: 608,
 1218: 609,
 1220: 610,
 1222: 611,
 1224: 612,
 1226: 613,
 1228: 614,
 1230: 615,
 1232: 616,
 1234: 617,
 1236: 618,
 1238: 619,
 1240: 620,
 1242: 621,
 1244: 622,
 1246: 623,
 1248: 624,
 1250: 625,
 1252: 626,
 1254: 627,
 1256: 628,
 1258: 629,
 1260: 630,
 1262: 631,
 1264: 632,
 1266: 633,
 1268: 634,
 1270: 635,
 1272: 636,
 1274: 637,
 1276: 638,
 1278: 639,
 1280: 640,
 1282: 641,
 1284: 642,
 1286: 643,
 1288: 644,
 1290: 645,
 1292: 646,
 1294: 647,
 1296: 648,
 1298: 649,
 1300: 650,
 1302: 651,
 1304: 652,
 1306: 653,
 1308: 654,
 1310: 655,
 1312: 656,
 1314: 657,
 1316: 658,
 1318: 659,
 1320: 660,
 1322: 661,
 1324: 662,
 1326: 663,
 1328: 664,
 1330: 665,
 1332: 666,
 1334: 667,
 1336: 668,
 1338: 669,
 1340: 670,
 1342: 671,
 1344: 672,
 1346: 673,
 1348: 674,
 1350: 675,
 1352: 676,
 1354: 677,
 1356: 678,
 1358: 679,
 1360: 680,
 1362: 681,
 1364: 682,
 1366: 683,
 1368: 684,
 1370: 685,
 1372: 686,
 1374: 687,
 1376: 688,
 1378: 689,
 1380: 690,
 1382: 691,
 1384: 692,
 1386: 693,
 1388: 694,
 1390: 695,
 1392: 696,
 1394: 697,
 1396: 698,
 1398: 699,
 1400: 700,
 1402: 701,
 1404: 702,
 1406: 703,
 1408: 704,
 1410: 705,
 1412: 706,
 1414: 707,
 1416: 708,
 1418: 709,
 1420: 710,
 1422: 711,
 1424: 712,
 1426: 713,
 1428: 714,
 1430: 715,
 1432: 716,
 1434: 717,
 1436: 718,
 1438: 719,
 1440: 720,
 1442: 721,
 1444: 722,
 1446: 723,
 1448: 724,
 1450: 725,
 1452: 726,
 1454: 727,
 1456: 728,
 1458: 729,
 1460: 730,
 1462: 731,
 1464: 732,
 1466: 733,
 1468: 734,
 1470: 735,
 1472: 736,
 1474: 737,
 1476: 738,
 1478: 739,
 1480: 740,
 1482: 741,
 1484: 742,
 1486: 743,
 1488: 744,
 1490: 745,
 1492: 746,
 1494: 747,
 1496: 748,
 1498: 749,
 1500: 750,
 1502: 751,
 1504: 752,
 1506: 753,
 1508: 754,
 1510: 755,
 1512: 756,
 1514: 757,
 1516: 758,
 1518: 759,
 1520: 760,
 1522: 761,
 1524: 762,
 1526: 763,
 1528: 764,
 1530: 765,
 1532: 766,
 1534: 767,
 1536: 768,
 1538: 769,
 1540: 770,
 1542: 771,
 1544: 772,
 1546: 773,
 1548: 774,
 1550: 775,
 1552: 776,
 1554: 777,
 1556: 778,
 1558: 779,
 1560: 780,
 1562: 781,
 1564: 782,
 1566: 783,
 1568: 784,
 1570: 785,
 1572: 786,
 1574: 787,
 1576: 788,
 1578: 789,
 1580: 790,
 1582: 791,
 1584: 792,
 1586: 793,
 1588: 794,
 1590: 795,
 1592: 796,
 1594: 797,
 1596: 798,
 1598: 799,
 1600: 800,
 1602: 801,
 1604: 802,
 1606: 803,
 1608: 804,
 1610: 805,
 1612: 806,
 1614: 807,
 1616: 808,
 1618: 809,
 1620: 810,
 1622: 811,
 1624: 812,
 1626: 813,
 1628: 814,
 1630: 815,
 1632: 816,
 1634: 817,
 1636: 818,
 1638: 819,
 1640: 820,
 1642: 821,
 1644: 822,
 1646: 823,
 1648: 824,
 1650: 825,
 1652: 826,
 1654: 827,
 1656: 828,
 1658: 829,
 1660: 830,
 1662: 831,
 1664: 832,
 1666: 833,
 1668: 834,
 1670: 835,
 1672: 836,
 1674: 837,
 1676: 838,
 1678: 839,
 1680: 840,
 1682: 841,
 1684: 842,
 1686: 843,
 1688: 844,
 1690: 845,
 1692: 846,
 1694: 847,
 1696: 848,
 1698: 849,
 1700: 850,
 1702: 851,
 1704: 852,
 1706: 853,
 1708: 854,
 1710: 855,
 1712: 856,
 1714: 857,
 1716: 858,
 1718: 859,
 1720: 860,
 1722: 861,
 1724: 862,
 1726: 863,
 1728: 864,
 1730: 865,
 1732: 866,
 1734: 867,
 1736: 868,
 1738: 869,
 1740: 870,
 1742: 871,
 1744: 872,
 1746: 873,
 1748: 874,
 1750: 875,
 1752: 876,
 1754: 877,
 1756: 878,
 1758: 879,
 1760: 880,
 1762: 881,
 1764: 882,
 1766: 883,
 1768: 884,
 1770: 885,
 1772: 886,
 1774: 887,
 1776: 888,
 1778: 889,
 1780: 890,
 1782: 891,
 1784: 892,
 1786: 893,
 1788: 894,
 1790: 895,
 1792: 896,
 1794: 897,
 1796: 898,
 1798: 899,
 1800: 900,
 1802: 901,
 1804: 902,
 1806: 903,
 1808: 904,
 1810: 905,
 1812: 906,
 1814: 907,
 1816: 908,
 1818: 909,
 1820: 910,
 1822: 911,
 1824: 912,
 1826: 913,
 1828: 914,
 1830: 915,
 1832: 916,
 1834: 917,
 1836: 918,
 1838: 919,
 1840: 920,
 1842: 921,
 1844: 922,
 1846: 923,
 1848: 924,
 1850: 925,
 1852: 926,
 1854: 927,
 1856: 928,
 1858: 929,
 1860: 930,
 1862: 931,
 1864: 932,
 1866: 933,
 1868: 934,
 1870: 935,
 1872: 936,
 1874: 937,
 1876: 938,
 1878: 939,
 1880: 940,
 1882: 941,
 1884: 942,
 1886: 943,
 1888: 944,
 1890: 945,
 1892: 946,
 1894: 947,
 1896: 948,
 1898: 949,
 1900: 950,
 1902: 951,
 1904: 952,
 1906: 953,
 1908: 954,
 1910: 955,
 1912: 956,
 1914: 957,
 1916: 958,
 1918: 959,
 1920: 960,
 1922: 961,
 1924: 962,
 1926: 963,
 1928: 964,
 1930: 965,
 1932: 966,
 1934: 967,
 1936: 968,
 1938: 969,
 1940: 970,
 1942: 971,
 1944: 972,
 1946: 973,
 1948: 974,
 1950: 975,
 1952: 976,
 1954: 977,
 1956: 978,
 1958: 979,
 1960: 980,
 1962: 981,
 1964: 982,
 1966: 983,
 1968: 984,
 1970: 985,
 1972: 986,
 1974: 987,
 1976: 988,
 1978: 989,
 1980: 990,
 1982: 991,
 1984: 992,
 1986: 993,
 1988: 994,
 1990: 995,
 1992: 996,
 1994: 997,
 1996: 998,
 1998: 999,
 ...}

In [115]:
l = list(range(1,100))

l.index(50)

49

In [ ]:
# Indexing
#

In [ ]:
# int, float, char, string
#

In [100]:
"//".join(["ab", "def"])

"//".join(["ab", "def", "ab", "def","ab", "def"])

'ab//def//ab//def//ab//def'

In [104]:
l = ["ab", "def", "ab", "def","ab", "def"]
s = l[0]
for i in l[1:]:
    s += "//" + i
    
print(s)

ab//def//ab//def//ab//def

In [87]:
{key:value for key, value in enumerate(range(0,1000,2))}

{0: 0,
 1: 2,
 2: 4,
 3: 6,
 4: 8,
 5: 10,
 6: 12,
 7: 14,
 8: 16,
 9: 18,
 10: 20,
 11: 22,
 12: 24,
 13: 26,
 14: 28,
 15: 30,
 16: 32,
 17: 34,
 18: 36,
 19: 38,
 20: 40,
 21: 42,
 22: 44,
 23: 46,
 24: 48,
 25: 50,
 26: 52,
 27: 54,
 28: 56,
 29: 58,
 30: 60,
 31: 62,
 32: 64,
 33: 66,
 34: 68,
 35: 70,
 36: 72,
 37: 74,
 38: 76,
 39: 78,
 40: 80,
 41: 82,
 42: 84,
 43: 86,
 44: 88,
 45: 90,
 46: 92,
 47: 94,
 48: 96,
 49: 98,
 50: 100,
 51: 102,
 52: 104,
 53: 106,
 54: 108,
 55: 110,
 56: 112,
 57: 114,
 58: 116,
 59: 118,
 60: 120,
 61: 122,
 62: 124,
 63: 126,
 64: 128,
 65: 130,
 66: 132,
 67: 134,
 68: 136,
 69: 138,
 70: 140,
 71: 142,
 72: 144,
 73: 146,
 74: 148,
 75: 150,
 76: 152,
 77: 154,
 78: 156,
 79: 158,
 80: 160,
 81: 162,
 82: 164,
 83: 166,
 84: 168,
 85: 170,
 86: 172,
 87: 174,
 88: 176,
 89: 178,
 90: 180,
 91: 182,
 92: 184,
 93: 186,
 94: 188,
 95: 190,
 96: 192,
 97: 194,
 98: 196,
 99: 198,
 100: 200,
 101: 202,
 102: 204,
 103: 206,
 104: 208,
 105: 210,
 106: 212,
 107: 214,
 108: 216,
 109: 218,
 110: 220,
 111: 222,
 112: 224,
 113: 226,
 114: 228,
 115: 230,
 116: 232,
 117: 234,
 118: 236,
 119: 238,
 120: 240,
 121: 242,
 122: 244,
 123: 246,
 124: 248,
 125: 250,
 126: 252,
 127: 254,
 128: 256,
 129: 258,
 130: 260,
 131: 262,
 132: 264,
 133: 266,
 134: 268,
 135: 270,
 136: 272,
 137: 274,
 138: 276,
 139: 278,
 140: 280,
 141: 282,
 142: 284,
 143: 286,
 144: 288,
 145: 290,
 146: 292,
 147: 294,
 148: 296,
 149: 298,
 150: 300,
 151: 302,
 152: 304,
 153: 306,
 154: 308,
 155: 310,
 156: 312,
 157: 314,
 158: 316,
 159: 318,
 160: 320,
 161: 322,
 162: 324,
 163: 326,
 164: 328,
 165: 330,
 166: 332,
 167: 334,
 168: 336,
 169: 338,
 170: 340,
 171: 342,
 172: 344,
 173: 346,
 174: 348,
 175: 350,
 176: 352,
 177: 354,
 178: 356,
 179: 358,
 180: 360,
 181: 362,
 182: 364,
 183: 366,
 184: 368,
 185: 370,
 186: 372,
 187: 374,
 188: 376,
 189: 378,
 190: 380,
 191: 382,
 192: 384,
 193: 386,
 194: 388,
 195: 390,
 196: 392,
 197: 394,
 198: 396,
 199: 398,
 200: 400,
 201: 402,
 202: 404,
 203: 406,
 204: 408,
 205: 410,
 206: 412,
 207: 414,
 208: 416,
 209: 418,
 210: 420,
 211: 422,
 212: 424,
 213: 426,
 214: 428,
 215: 430,
 216: 432,
 217: 434,
 218: 436,
 219: 438,
 220: 440,
 221: 442,
 222: 444,
 223: 446,
 224: 448,
 225: 450,
 226: 452,
 227: 454,
 228: 456,
 229: 458,
 230: 460,
 231: 462,
 232: 464,
 233: 466,
 234: 468,
 235: 470,
 236: 472,
 237: 474,
 238: 476,
 239: 478,
 240: 480,
 241: 482,
 242: 484,
 243: 486,
 244: 488,
 245: 490,
 246: 492,
 247: 494,
 248: 496,
 249: 498,
 250: 500,
 251: 502,
 252: 504,
 253: 506,
 254: 508,
 255: 510,
 256: 512,
 257: 514,
 258: 516,
 259: 518,
 260: 520,
 261: 522,
 262: 524,
 263: 526,
 264: 528,
 265: 530,
 266: 532,
 267: 534,
 268: 536,
 269: 538,
 270: 540,
 271: 542,
 272: 544,
 273: 546,
 274: 548,
 275: 550,
 276: 552,
 277: 554,
 278: 556,
 279: 558,
 280: 560,
 281: 562,
 282: 564,
 283: 566,
 284: 568,
 285: 570,
 286: 572,
 287: 574,
 288: 576,
 289: 578,
 290: 580,
 291: 582,
 292: 584,
 293: 586,
 294: 588,
 295: 590,
 296: 592,
 297: 594,
 298: 596,
 299: 598,
 300: 600,
 301: 602,
 302: 604,
 303: 606,
 304: 608,
 305: 610,
 306: 612,
 307: 614,
 308: 616,
 309: 618,
 310: 620,
 311: 622,
 312: 624,
 313: 626,
 314: 628,
 315: 630,
 316: 632,
 317: 634,
 318: 636,
 319: 638,
 320: 640,
 321: 642,
 322: 644,
 323: 646,
 324: 648,
 325: 650,
 326: 652,
 327: 654,
 328: 656,
 329: 658,
 330: 660,
 331: 662,
 332: 664,
 333: 666,
 334: 668,
 335: 670,
 336: 672,
 337: 674,
 338: 676,
 339: 678,
 340: 680,
 341: 682,
 342: 684,
 343: 686,
 344: 688,
 345: 690,
 346: 692,
 347: 694,
 348: 696,
 349: 698,
 350: 700,
 351: 702,
 352: 704,
 353: 706,
 354: 708,
 355: 710,
 356: 712,
 357: 714,
 358: 716,
 359: 718,
 360: 720,
 361: 722,
 362: 724,
 363: 726,
 364: 728,
 365: 730,
 366: 732,
 367: 734,
 368: 736,
 369: 738,
 370: 740,
 371: 742,
 372: 744,
 373: 746,
 374: 748,
 375: 750,
 376: 752,
 377: 754,
 378: 756,
 379: 758,
 380: 760,
 381: 762,
 382: 764,
 383: 766,
 384: 768,
 385: 770,
 386: 772,
 387: 774,
 388: 776,
 389: 778,
 390: 780,
 391: 782,
 392: 784,
 393: 786,
 394: 788,
 395: 790,
 396: 792,
 397: 794,
 398: 796,
 399: 798,
 400: 800,
 401: 802,
 402: 804,
 403: 806,
 404: 808,
 405: 810,
 406: 812,
 407: 814,
 408: 816,
 409: 818,
 410: 820,
 411: 822,
 412: 824,
 413: 826,
 414: 828,
 415: 830,
 416: 832,
 417: 834,
 418: 836,
 419: 838,
 420: 840,
 421: 842,
 422: 844,
 423: 846,
 424: 848,
 425: 850,
 426: 852,
 427: 854,
 428: 856,
 429: 858,
 430: 860,
 431: 862,
 432: 864,
 433: 866,
 434: 868,
 435: 870,
 436: 872,
 437: 874,
 438: 876,
 439: 878,
 440: 880,
 441: 882,
 442: 884,
 443: 886,
 444: 888,
 445: 890,
 446: 892,
 447: 894,
 448: 896,
 449: 898,
 450: 900,
 451: 902,
 452: 904,
 453: 906,
 454: 908,
 455: 910,
 456: 912,
 457: 914,
 458: 916,
 459: 918,
 460: 920,
 461: 922,
 462: 924,
 463: 926,
 464: 928,
 465: 930,
 466: 932,
 467: 934,
 468: 936,
 469: 938,
 470: 940,
 471: 942,
 472: 944,
 473: 946,
 474: 948,
 475: 950,
 476: 952,
 477: 954,
 478: 956,
 479: 958,
 480: 960,
 481: 962,
 482: 964,
 483: 966,
 484: 968,
 485: 970,
 486: 972,
 487: 974,
 488: 976,
 489: 978,
 490: 980,
 491: 982,
 492: 984,
 493: 986,
 494: 988,
 495: 990,
 496: 992,
 497: 994,
 498: 996,
 499: 998}

In [244]:
number = float(input("value:"))
if number > 0 :
    print("the %2.3f is positive no" %number)
elif number < 0:
    print("the number is negative number")
else:
    print("the number is zero")

value:3542.342
the 3542.342 is positive no

In [245]:
'''In this program, we input a number
check if the number is positive or
negative or zero and display
an appropriate message
This time we use nested if statement'''

num = float(input("Enter a number: "))
if num >= 0:
    if num == 0:
        print("Zero")
    else:
        print("Positive number")
else:
    print("Negative number")

Enter a number: 3334
Positive number

In [246]:
def multiply(x):
    return x*3
multiply(3)

9

In [247]:
list_ = [1,2,4,5,6,7788,7,5,7,5]
list(map(multiply,list_))

[3, 6, 12, 15, 18, 23364, 21, 15, 21, 15]

In [248]:
list(map(lambda x:x*3,list_))

[3, 6, 12, 15, 18, 23364, 21, 15, 21, 15]

In [252]:
f=lambda y: y**2

In [253]:
f(5)

25

In [257]:
list(filter(lambda x: x>4,list_))

[5, 6, 7788, 7, 5, 7, 5]

In [262]:
from functools import reduce

a = [(1,2),(4,5)]
reduce(lambda x,y:x+y,a), sum(a, ())

((1, 2, 4, 5), (1, 2, 4, 5))

In [259]:
sum(list_)

7830

In [263]:
## and or in not is

In [264]:
x = range(1,101)
sum(x)

5050

In [265]:
30 in list_

False

In [269]:
x = 2
y =4
z = x

x is z

True

sum(range(1,11))

In [2]:
%%timeit
sum(range(1,100000))

7.19 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [4]:
%%timeit
sum=0
for x in range (1,100000):
    sum += x


sum

16.4 ms ± 285 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

SyntaxError: invalid syntax (Temp/ipykernel_31816/363547303.py, line 1)

In [23]:
a = ['a','s','c','w','q']
# for x in range(0,len(a),2):
#     print(a[x])
not_to_print = ["s", "c"]

for i in a:
    if i in not_to_print:
        continue
        
    print(i)

a
w
q

In [24]:
a =list(range(1,50,4))
a.

In [29]:
b = tuple(a)
b.

1

In [39]:
def fac(x):
    if(x==1):
        return(x)
    elif x<=0:
        print("invalid number")
     
    
    else:
        return(x*fac(x-1))
y=int(input("enter value"))

print("factorial of ",y,"is",fac(y))

enter value0
invalid number
factorial of  0 is None

In [42]:
def multiply(x):
    return x*2
multiply(3)

list_=[1,2,4,5,6,8,0]
list(map(multiply,list_))

[2, 4, 8, 10, 12, 16, 0]

In [43]:
list(map(lambda x:x**2,list_))

[1, 4, 16, 25, 36, 64, 0]

In [45]:
p=lambda x:x**x
p(4)

256

In [46]:
s = list(filter(lambda x: (x%2==0),list_))
print(s)

[2, 4, 6, 8, 0]

In [47]:
a = 5

print(type(a))

print(type(5.0))

c = 5 + 3j
print(c + 3)

print(isinstance(c, complex))

<class 'int'>
<class 'float'>
(8+3j)
True

In [51]:
import math as m
n = int(input("enter the value"))
x = m.factorial(n)
print("factorial of",n,"is",x)

enter the value8
factorial of 8 is 40320

In [52]:
# define Python user-defined exceptions
class Error(Exception):
    """Base class for other exceptions"""
    pass


class ValueTooSmallError(Error):
    """Raised when the input value is too small"""
    pass


class ValueTooLargeError(Error):
    """Raised when the input value is too large"""
    pass


# you need to guess this number
number = 10

# user guesses a number until he/she gets it right
while True:
    try:
        i_num = int(input("Enter a number: "))
        if i_num < number:
            raise ValueTooSmallError
        elif i_num > number:
            raise ValueTooLargeError
        break
    except ValueTooSmallError:
        print("This value is too small, try again!")
        print()
    except ValueTooLargeError:
        print("This value is too large, try again!")
        print()

print("Congratulations! You guessed it correctly.")

Enter a number: 2
This value is too small, try again!

Enter a number: 6
This value is too small, try again!

Enter a number: 13
This value is too large, try again!

Enter a number: 10
Congratulations! You guessed it correctly.